### ISSUE TITLE
Is the deletion of Misc/Entries possible as well?

### ISSUE THREAD

**Issue by 5T33Z0** [dreamwhite/Catone#1]
Hi.

I looked into your script and noticed taht there's no option to automatically delete custom entries from the config.plist. I was thinking about somelthing like this:

```
def delete_misc_entries(self) -> None:
""" Deletes custom bootloader entries from config.plist"""
self.plist['Misc']['Entries']…??
```
But I don't know what to add after that to delete the entries. Since Misc/Entries are stores as Dictionaries it probably should delete any dict in that array, right?

**Comment by dreamwhite** [comment]
Hi, thank you so much for reaching me out. From what I tested, `Misc/Entries` is an array of dicts, so in case you wanna clear it you can just add `self.plist['Misc']['Entries'] = []`. Feel free to open a PR so I can keep track of changes easily

**Comment by 5T33Z0** [comment]
Thanks. It works.

**Comment by dreamwhite** [comment]
@5T33Z0  Since the same applies to `Misc/BlessOverride` can you open a PR that includes it? Thanks :D

**Comment by 5T33Z0** [comment]
I will create a fork and include the changes. But I would like to use a different name for the repo. Something more obvious like "OC Config Anonymizer" or "OC Config Defaultizer" or something. Is that ok for you?

**Comment by 5T33Z0** [comment]
Interesting. Okay, cool. I only have to figure out how renaming a fork works

**Comment by dreamwhite** [comment]
I think I should rename it. Give me a few mins

**Comment by dreamwhite** [comment]
Done, let me know if it suits or not and eventually fork it again
